services:
  sas_robot_driver_ur:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      TIMEOUT: 20
    command: /bin/bash -c "
      cd /root/sas_robot_driver_ur_devel/src/sas_robot_driver_ur/docker
      && chmod +x test.sh
      && ./test.sh"
